sat_preproc:
  sat_names: ['CFOSAT','Cryosat-2','AltiKa','HY-2B','Jason-3','Sentinel-3A', 'Sentinel-3B']
  years: [2023]
  sat_specifics:
    lat: 'latitude'
    lon: 'longitude'
    time: 'time'
    hs: 'VAVH'
    type: 'L3'
  paths:
    sat: '/work/opa/md04916/iride/WAVE_GLO_PHY_SWH_L3_NRT_014_001/{satName}/{year}/{month}/'
    output: '/work/opa/sc33616/ww3/tools/iride_puglia'
  filenames:
    sat:
      template: 'global_vavh_l3_rt_*_*.nc'
      cicle: '*'
      passage: '*'
    output: '{sat_name}_{year}'
  processing:
    boundingBox:
      xmin: 12.40
      xmax: 21.31
      ymin: 38.44
      ymax: 46.34
    filters:
      quality_check:
         variable_name: False  #qual_alt_1hz_swh_ku  ## Set to False to skip, else set the variable name
         value: 0                                         # set the idenfifier for good data
      land_masking:
        variable_name: False #'surface_type' ## Set to False to skip, else set the variable name
        value: 0                                          # set the idenfifier for the ocean
        shapefile: "/work/opa/sc33616/ww3/tools/scatter_waves/data/shp/puglia_coast.shp" #'/Users/scausio/Documents/data/shapefile/blackSea_poly/bs.shp' #shapefile of your valid model domain.  if shapefile: False the tool masks land according to the dataset flag, otherwise it use the ocean shapefile
      threshold:
        min: 0.25 # discard Hs< min
        max: 6    # discard Hs> max
      zscore:
        sigma: 3  

model_preproc:
  out_dir: '/work/opa/sc33616/ww3/tools/iride_puglia'
  datasets:
   sat:
     path: '/work/opa/sc33616/ww3/tools/iride_puglia/{year}_CMEMS_SAT_threshold_landMasked_qcheck_zscore{sigma}.nc' #'/work/opa/sc33616/ww3/bs_validation/data/{year}_j2_blackSea_zscore3.nc'  #'/work/opa/sc33616/ww3/tools/satTest_manu/CFOSAT_{year}_threshold_landMasked_qcheck_zscore3.nc'  #'/work/opa/sc33616/ww3/tools/satTest_manu/{year}_CMEMS_SAT_threshold_landMasked_qcheck_zscore3.nc' #'/work/opa/sc33616/ww3/bs_validation/data/{year}_j2_blackSea_zscore3.nc'
     lat: 'latitude'
     lon: 'longitude'
     time: 'time'
   models: # for validation of more exps please repeat the code block 'yourExp1' naming it as you prefer
     #wam:
     #  path: '/data/inputs/metocean/historical/model/ocean/HCMR/WAM_CMEMS/analysis/1h/{year}/*/*-WAVE-MEDWAM3-MEDATL-*-sv06.00.nc'
     #  experiment: "*"
     #  lat: 'latitude'
     #  lon: 'longitude'
     #  hs: 'VHM0'
     #  time: 'time'
     adriatic:
       #path: '/work/opa/ww3_cst/runs/adriatic/output_adr2019-2020/ww3.201*.nc'
       path: '/work/opa/sc33616/ww3/tools/iride/adri/ww3*.nc' #'/work/opa/ww3_cst/runs/{experiment}/20191231/netcdf/ww3.*.nc'
       lat: 'latitude'
       lon: 'longitude'
       hs: 'hs'
       time: 'time'
  filters:
    max_distance_in_space: 0.04                         # (in degree) it discards data if sat is farther this value
    max_distance_in_time: 1                             # (in hours) it discards data if sat is farther this value
    threshold:
      min: 0.25
      max: 6
plot:
  satName: 'CFOSAT [m]' #,Cryosat-2,AltiKa,HY-2B,Jason-3,Sentinel-3A,Sentinel-3B [m]' # this is a string in the plot title
  experiments: # experiments you want to plot
    # wam:
    #  series: '/work/opa/sc33616/ww3/tools/unst_Adr/wam_{year}_series.npy'
    #adriatic:
    #  series: '/work/opa/sc33616/ww3/tools/unst_Adr_2023/{experiment}_{year}_series.npy' # '/work/opa/sc33616/ww3/tools/satTest_manu/yourExp1_{year}_series.npy'
    adriatic:
      series: '/work/opa/sc33616/ww3/tools/iride_puglia/{experiment}_{year}_sat_series.nc'
  expName: 'adr_{exp}_{year}'
  out_dir: '/work/opa/sc33616/ww3/tools/iride_puglia/plots'
  additional_filters:
    ntimes: 2 # mask data if satellite hs is > of ntimes * model hs




